<a href="https://colab.research.google.com/github/Dhanush777max/AIML/blob/main/AIML_1_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas
list = [1,2,3]
print(list)
a = np.array([1,2,3])
print(a)
b = type(a)
print(b)
c = np.array([1,2,3])
d = a+c
print(d)
e = a*2
print(e)
f = a/2
print(f)
g = a-2
print(g)
h = a**2
print(h)
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

[1, 2, 3]
[1 2 3]
<class 'numpy.ndarray'>
[2 4 6]
[2 4 6]
[0.5 1.  1.5]
[-1  0  1]
[1 4 9]
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[ 1.55740772 -2.18503986 -0.14254654]
